### ISSUE TITLE
Mean-max pooling

### ISSUE THREAD

**Issue by ducha-aiki** [cypw/DPNs#1]
Hi,

You write that if one​ have seen mean-max pooling, then let you know :)

Such pooling was proposed in 
Generalizing Pooling Functions in Convolutional Neural Networks: Mixed, Gated, and Tree
Chen-Yu Lee, Patrick W. Gallagher, Zhuowen Tu
AISTATS 2016
http://arxiv.org/abs/1509.08985

I have tested it in my benchmark https://github.com/ducha-aiki/caffenet-benchmark/blob/master/Pooling.md

The only difference is that max-average pooling wasn't applied to the last layer.

**Comment by cypw** [comment]
Thank you. 

I've added this related work and updated the paper.

In addition to the difference that you’ve mentioned above, the introduced mean-max pooling strategy also does not require any training or fine-tuning. But, it would be interesting to see the effect if such mean-max pooling strategy is applied to DPNs for both training and testing.

**Comment by enjoyyi00** [comment]
do you have any implement of Mean-Max Pooling?

**Comment by cypw** [comment]
@iFighting 
see [score.py#L58](https://github.com/cypw/DPNs/blob/master/score.py#L58).

**Comment by enjoyyi00** [comment]
thanks @cypw
