### ISSUE TITLE
Why "num_filter=(num_1x1_c+2*inc)" instead of "num_filter=(num_1x1_c+inc)"

### ISSUE THREAD

**Issue by rouniuyizu** [cypw/DPNs#11]
line 30 in DPNs/settings/symbol_dpn.py

c1x1_w   = BN_AC_Conv( data=data_in, num_filter=(num_1x1_c+2*inc), kernel=( 1, 1), stride=(key_stride, key_stride), name=('%s_c1x1-w(s/%d)' %(name, key_stride)), pad=(0, 0))

**Comment by cypw** [comment]
I believe more information should be kept for these downsampling layers compared with normal layers.
So, I set it to `2*inc` for these downsampling layers based on my previous experience.

**Comment by rouniuyizu** [comment]
Got it. Thanks,
