### ISSUE TITLE
I want to detect objects by DPNs

### ISSUE THREAD

**Issue by Harold-Zhang** [cypw/DPNs#12]
How to train a model to detect objects and get results？ May I use the pretrained models？

**Comment by Harold-Zhang** [comment]
@cypw

**Comment by cypw** [comment]
There are many examples showing how to use a pre-trained model to do object detection in MXNet, such as:
1) Faster R-CNN in MXNet: [mx-rcnn](https://github.com/precedenceguo/mx-rcnn)
2) SSD in MXNet: [mxnet-ssd](https://github.com/zhreshold/mxnet-ssd)

You can get started by following their README files and substitute the base CNN with DPN.

**Comment by Harold-Zhang** [comment]
@cypw Thanks for your reply. I saw the result of ILSVRC2017 Object detection on Image-Net, and your team used the ensemble of DPN models to detect objects, how did it work? Did you use DPNs? Or Faster R-CNN? Thank you~

**Comment by Harold-Zhang** [comment]
@cypw

**Comment by Harold-Zhang** [comment]
@cypw Could you provide me some paper about your DPNs? I want to learn more but I didn't find more paper except ILSVRC2017 workshop. By the way, could you tell me how long it took you to train DPN-92 model with 4 x K80? Thanks for your help.

**Comment by cypw** [comment]
@Harold-Zhang Thank you for your interest.

In the competition, we used the Faster R-CNN framework and substituted the base CNN with different kinds of DPNs and did the ensembling. Several tricks are used to boost the performance and you can check our team's abstract at \[[here](http://image-net.org/challenges/LSVRC/2017/results)\] for more information.

Besides the workshop \[[slides](http://image-net.org/challenges/talks_2017/ilsvrc2017_DPNs.pdf)\], we also have a \[[paper](https://arxiv.org/abs/1707.01629)\] and a \[[video](https://pan.baidu.com/s/1skEPhN3)\](in chinese) talking about the proposed DPNs.

As for the training time, DPN-92 takes about one day using a cluster with 40 x K80 cards. The actual training speed of each node is shown at \[[here](https://github.com/cypw/DPNs#efficiency-training)\]. I haven't tried to train DPNs on a single node, but I guess it may take you more than a week to train DPN-92 from scratch.

**Comment by Harold-Zhang** [comment]
Thank you very much!@cypw
