### ISSUE TITLE
DPN-98 on Place365-Standard dataset

### ISSUE THREAD

**Issue by shipengai** [cypw/DPNs#15]
Hi,
    Thank for your sharing. But I want to use DPn-98 or Dpn-92 pretrained model on Place365-Standard dataset,
Can you give me a site?
   Thank you very much

**Comment by cypw** [comment]
@shipeng-uestc Thank you for your interest.

DPN-92 pretrained model on Place365-Standard:
- [GoogleDrive](https://goo.gl/fRq1YM)

Validation list & Matlab code* for 10 crops testing for DPN pretrained model.
- [GoogleDrive](https://goo.gl/jQkMpr)

*Note: you can tune the testing params, e.g. enlarge input slen, enlarge crop size, use more crops, etc, for better performance.

**Comment by shipengai** [comment]
Thank you for your answer!
