### ISSUE TITLE
Need substrated mean RGB = [124,117,104] on DPN-68 of imagenet-5k?

### ISSUE THREAD

**Issue by rong2010** [cypw/DPNs#21]
Dear cypw,
      After i download the pre-trained model name dpn68-5k_2017_08_18.tar.gz.I find the result is wrong if i substrated mean rgb, Need  substrated mean RGB?

**Comment by cypw** [comment]
Yes, I use the same normalization strategy for all DPN models, i.e. "the input images are substrated by mean RGB = [ 124, 117, 104 ], and then multiplied by 0.0167".

**Comment by rong2010** [comment]
Dear cypw,
     Thank you for your reply.I test two models named the pre-trained dpn68_2017_08_18.tar.gz and dpn68-5k_2017_08_18.tar.gz.
     The predict result of dpn68-1k is ok. I predit five images, the three images predict the classid is 764. However,the predict result of dpn68-5k is hard to understand.The five image is belong to classid 'n04090263' predict different outcomes.
 
[mxnet_predict.zip](https://github.com/cypw/DPNs/files/1954488/mxnet_predict.zip)
[predict_result.txt](https://github.com/cypw/DPNs/files/1954489/predict_result.txt)

**Comment by BigFishMaster** [comment]
@rong2010  How to solve the problem you metioned above??

**Comment by cypw** [comment]
Hi, 

The mismatched prediction is because of the wrong train/val list. 

I didn't realize it until @BigFishMaster pointed it out. 

Sorry for the inconvenience. I've updated the link.
